name: arr-bazarr  # Stack & directory name
networks:
  arrstack_network:
    external: true
services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA_PATH}/bazarr:/config
      - ${MEDIA_PATH}/media:/data/media
    ports:
      - 6767:6767
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: unless-stopped
    networks:
      - arrstack_network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    deploy:
      resources:
        reservations:
          memory: 64MB
          cpus: "0.00"
        limits:
          memory: 4GB
          cpus: "1.00"
x-casaos:
  main: bazarr
  port_map: "6767"
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.bazarr/assets/icon.svg
  title:
    en_US: Bazarr
    custom: Bazarr
  #version: 1.5.6 #(2026.09)