name: arr-sabnzbd  # Stack & directory name
networks:
  arrstack_network:
    external: true
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - ${APPDATA_PATH}/sabnzbd:/config
      - ${MEDIA_PATH}:/data
    ports:
      - 8282:8080  # Modified so it coexists with qBittorrent here.
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}   
    restart: unless-stopped
    networks:
      - arrstack_network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    deploy:
      resources:
        reservations:
          memory: 64MB
          cpus: "0.00"
        limits:
          memory: 4GB
          cpus: "1.00"
x-casaos:
  main: sabnzbd
  port_map: "8282"
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.sabnzbd/assets/icon.svg
  title:
    en_US: Sabnzbd
    custom: Sabnzbd
  #version: 5.0.3 #(2026.09)